version: '3.8'
services:
  database:
    image: 'postgres:15.2-alpine'
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - "./.docker/database:/var/lib/postgresql/data"
